services:
  db:
    image: postgres:16
    container_name: inventory-postgres
    environment:
      POSTGRES_DB: inventory
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  adminer:
    image: adminer:4
    container_name: inventory-adminer
    ports:
      - "8080:8080"
volumes:
  pgdata:
